version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Kaddex Stats API
      - APP_VERSION=1.0
      - PORT=5000
      - MONGO_DB_URI=mongodb://mongo/nest
      - CHAINWEB_NODE_URL=https://api.chainweb.com
      - CHAINWEB_NETWORK_ID=mainnet01
      - CHAIN_ID=2
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: